#!/usr/bin/env bash
# This is a bash script that transfers a file to the server.

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/; then
		echo "File transferred successfully to $2"
	else
		echo "Transfer failed..."
	fi
fi
