#!/usr/bin/env bash
# Bash script that configures an Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > sudo tee /var/www/html/yasin.html
echo  "server {
	listen 80;

	listen [::]:80 default_server;

	root /var/www/html;

	index hassan.html index.html index.nginx-debian.html;

	location /redirect_me {

		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
