#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer for two web servers.

sudo apt-get -y update
sudo apt-get -y install haproxy
#sudo apt-get install --no-install-recommends software-properties-common
#sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
#sudo apt-get update
#sudo apt-get install haproxy=2.8.\*
#sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo echo "
	frontend my_frontend
		bind *:80
		default_backend my_backend

	backend my_backend
		balance roundrobin
		server 369701-web-01 52.91.119.249:80 check
		server 369701-web-02 54.236.51.82:80 check
	" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
