#!/usr/bin/env bash
# a bash script that manages "manage_my_process".

if [ "$1" == "start" ]; then
	echo "manage_my_process started"
	./manage_my_process &
	sudo touch /var/run/my_process.pid
	echo $$ > /var/run/my_process.pid
elif [ "$1" == "stop" ]; then
	echo "manage_my_process stopped"
	sudo pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
elif [ "$1" == "restart" ]; then
	echo "manage_my_process restarted"
	sudo pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
	./manage_my_process &
	sudo touch /var/run/my_process.pid
	echo $$ > /var/run/my_process.pid
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
