#!/usr/bin/env bash
#This script displays numbers from 1 to 20 with special messages for specific numbers
hb=1
while [ $hb -le 20 ]
do
    echo $hb
    case $hb in
    4)
    echo $hb
    echo "bad luck from China";;
    9)
    echo $hb
    echo "bad luck from Japan";;
    17)
    echo $hb
    echo "bad luck from Italy";;
   esac
    hb=$((hb+1))
done
